### ISSUE TITLE
Formula garbled

### ISSUE THREAD

**Issue by 0xSecYou** [adshao/publications#3]
> 师傅您好，您的文章写得很好，但就是解读白皮书的文章中的公式出现了乱码问题，阅读起来有点不太方便，乱码的原因是因为在公式中添加了标签 \tag{}😁

**Comment by adshao** [comment]
> > 师傅您好，您的文章写得很好，但就是解读白皮书的文章中的公式出现了乱码问题，阅读起来有点不太方便，乱码的原因是因为在公式中添加了标签 \tag{}😁

谢谢，能否截图看看具体哪篇文章哪个公式有问题？

**Comment by 0xSecYou** [comment]
在uniswapv2和uniswapv3白皮书的讲解中：
![image](https://github.com/user-attachments/assets/5b337129-94e6-4ad6-9864-65c27af982cc)

**Comment by adshao** [comment]
hi @LBiyou , 谢谢提醒，最近刚想起这个问题，已经修复了。
